### ISSUE TITLE
Linux download link is broken

### ISSUE THREAD

**Issue by jaydson** [zeit/hyper-website#47]
The download link for Linux is broken.
https://hyper-updates.now.sh/download/linux

```
Version not found: latest
```

**Comment by montyanderson** [comment]
yeah. I was just about to start an issue with this!

**Comment by montyanderson** [comment]
to anyone reading: you can go to https://github.com/zeit/hyper/releases and download the latest Linux deb from there.

**Comment by CodeTheory** [comment]
This is an issue with the release system of Hyper itself. Will be fixed in the next release. For now, you can download Linux files from https://github.com/zeit/hyper/releases
