### ISSUE TITLE
Hyper for Linux Link broken

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [zeit/hyper-website#60]
Go to https://hyper.is/#installation, click on "linux" and you'll get a white page with the text "Version not found: latest" in top left corner.

**Comment by CodeTheory** [comment]
Hi @hubertgrzeskowiak. Thanks for the issue. This will be fixed in the next Hyper release! For now you can grab the download for linux under the Hyper releases section in GitHub (https://github.com/zeit/hyper/releases/latest) 👍

**Comment by hubertgrzeskowiak** [comment]
Oh, just realized this was already covered in #47. Nevermind then and thanks. Keep up the good work.
