### ISSUE TITLE
Ctrl+C, Ctrl+D aren't parsed by Windows Command Prompt/Powershell

### ISSUE THREAD

**Issue by rainyday** [zeit/hyper-website#67]
Pressing Ctrl+C in the windows command prompt in 1.0.0 doesn't do anything, Pressing Ctrl+D simply prints out "^D" instead of killing the current process. In msys bash these commands behave as expected so this is specific to cmd and Powershell.

**Comment by CodeTheory** [comment]
Hi @rainyday, could you submit this issue to the [Hyper repo](https://github.com/zeit/hyper/issues/new) instead?

**Comment by rainyday** [comment]
Oh, whoops, sorry about that.

**Comment by CodeTheory** [comment]
No problem. You'll likely get more help there 😛 .
